$CustomTrain_MSG_1 = GetTranslatedFileIni("sam m0d log msg", "Training Troops & Spells", "Training Troops & Spells")
$CustomTrain_MSG_2 = GetTranslatedFileIni("sam m0d log msg", "Waiting for troops ready", "Waiting for troops ready...")
$CustomTrain_MSG_3 = GetTranslatedFileIni("sam m0d log msg", "Check troops queue in train", "Check troops queue in train, is that any troops stuck...")
$CustomTrain_MSG_4 = GetTranslatedFileIni("sam m0d log msg", "Your Army Camps are now Full", "Your Army Camps are now Full")
$CustomTrain_MSG_5 = GetTranslatedFileIni("sam m0d log msg", "Prepare for train number Of", "Prepare for train number Of")
$CustomTrain_MSG_6 = GetTranslatedFileIni("sam m0d log msg", "Ready to train", "Ready to train")
$CustomTrain_MSG_7 = GetTranslatedFileIni("sam m0d log msg", "with total", "with total")
$CustomTrain_MSG_8 = GetTranslatedFileIni("sam m0d log msg", "Not enough", "Not enough")
$CustomTrain_MSG_9 = GetTranslatedFileIni("sam m0d log msg", "to train", "to train")
$CustomTrain_MSG_10 = GetTranslatedFileIni("sam m0d log msg", "Prepare for brew number Of", "Prepare for brew number Of")
$CustomTrain_MSG_11 = GetTranslatedFileIni("sam m0d log msg", "Current", "Current")
$CustomTrain_MSG_12 = GetTranslatedFileIni("sam m0d log msg", "Troop cost", "Troop cost")
$CustomTrain_MSG_13 = GetTranslatedFileIni("sam m0d log msg", "Spell cost", "Spell cost")
$CustomTrain_MSG_14 = GetTranslatedFileIni("sam m0d log msg", "Ready to brew", "Ready to brew")
$CustomTrain_MSG_15 = GetTranslatedFileIni("sam m0d log msg", "Please setup your troops at the M0d section.", "Please setup your troops at the M0d section.")
$CustomTrain_MSG_DarkElixir = GetTranslatedFileIni("sam m0d log msg", "Dark Elixir", "Dark Elixir")
$CustomTrain_MSG_Elixir = GetTranslatedFileIni("sam m0d log msg", "Elixir", "Elixir")



